#!/usr/bin/env python3
"""Bundle viewer/instrument.html into one self-contained HTML file.

The point is a file you can paste anywhere -- IPFS, a gist, an email
attachment -- and have it open into the orbitable instrument with no network
access of any kind. three.js r184 is fetched once from unpkg, checked against
the integrity map already pinned in viewer/instrument.html, and inlined.

The page's <style> and its .wrap markup are both lifted out of
viewer/instrument.html, so the bundle cannot show something the source page
does not. Every payload rides in a <script type="text/plain"> block and is
handed to the page as a blob: URL at load time. That indirection is what lets a single file
carry ES modules: an import map is built at runtime pointing the bare 'three'
specifier at the blob, before the first module script is inserted.

    python3 tools/build_single_file_viewer.py -o instrument-standalone.html
"""

import argparse
import base64
import hashlib
import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VIEWER = ROOT / "viewer"
SOURCE = VIEWER / "instrument.html"

# id -> URL path under the three package. The hashes are NOT written here on
# purpose: they are read out of instrument.html's integrity map, so the page
# stays the single source of truth for which three.js this project trusts.
CDN = {
    "p-core":  "build/three.core.js",
    "p-three": "build/three.module.js",
    "p-orbit": "examples/jsm/controls/OrbitControls.js",
    "p-obj":   "examples/jsm/exporters/OBJExporter.js",
    "p-gltf":  "examples/jsm/exporters/GLTFExporter.js",
}

BOOT = """
(function () {
  var txt = function (id) { return document.getElementById(id).textContent; };
  var blob = function (src) {
    return URL.createObjectURL(new Blob([src], { type: 'text/javascript' }));
  };

  // three.module.js pulls its own core in by relative path, which cannot
  // resolve from a blob: URL. Rewrite it to the core's blob first.
  var core = blob(txt('p-core'));
  var three = blob(txt('p-three').split('THREE_CORE_BLOB_URL').join(core));

  // The import map has to be installed before any module script loads, so
  // this whole bootstrap is a classic script and runs synchronously.
  var im = document.createElement('script');
  im.type = 'importmap';
  im.textContent = JSON.stringify({ imports: {
    'three': three,
    'three/addons/controls/OrbitControls.js': blob(txt('p-orbit')),
    'three/addons/exporters/OBJExporter.js': blob(txt('p-obj')),
    'three/addons/exporters/GLTFExporter.js': blob(txt('p-gltf'))
  }});
  document.head.appendChild(im);

  var stage = document.createElement('script');  // classic: defines the element
  stage.textContent = txt('p-stage');
  document.head.appendChild(stage);

  var model = document.createElement('script');  // module: builds the instrument
  model.type = 'module';
  model.src = blob(txt('p-model'));
  document.body.appendChild(model);
})();
"""

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s</title>
<meta name="description" content="%(description)s">
<link rel="icon" href="%(favicon)s">
<!-- Link preview. Without these a shared URL renders as a bare blue link, and
     for a page whose entire content is a WebGL canvas there is nothing for a
     crawler to fall back on -- no heading, no paragraph, no image. The card
     image has to be an absolute URL because crawlers fetch it out of band;
     a data: URI will not do. -->
<meta property="og:type" content="website">
<meta property="og:url" content="%(url)s">
<meta property="og:title" content="%(card_title)s">
<meta property="og:description" content="%(description)s">
<meta property="og:image" content="%(image)s">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="%(card_title)s">
<meta name="twitter:description" content="%(description)s">
<meta name="twitter:image" content="%(image)s">
<!--
  Self-contained build of viewer/instrument.html -- three.js r184 inlined,
  zero network requests. Drag to orbit, scroll to zoom, and use the toolbar to
  export OBJ or GLB.

  Generated by tools/build_single_file_viewer.py. Do not hand-edit; regenerate.
-->
<style>%(style)s</style>
</head>
<body>
%(body)s
<noscript>
  <!-- The page is a WebGL canvas and nothing else, so without scripting it is
       a black rectangle with no explanation. Say what it was and where to go. -->
  <div style="position:fixed;inset:0;display:flex;align-items:center;
              justify-content:center;background:#0c0c0b;color:#D8D2C8;
              font:14px/1.7 Helvetica Neue,Helvetica,Arial,sans-serif;
              text-align:center;padding:2rem">
    <div>
      <p style="letter-spacing:3px;margin:0 0 .6rem">CELL</p>
      <p style="color:#8A8B8F;margin:0 0 1.2rem">
        This page is an interactive 3D model of the instrument.<br>
        It needs JavaScript and WebGL.
      </p>
      <a href="https://github.com/z0r0z/cell" style="color:#B23A48">github.com/z0r0z/cell</a>
    </div>
  </div>
</noscript>

%(payloads)s

<script>%(boot)s</script>
</body>
</html>
"""


def favicon_data_uri():
    """viewer/favicon.svg as an inline data: URI.

    Percent-encoded rather than base64: it survives the round trip just as
    reliably, stays readable in View Source, and costs a third less.
    """
    svg = (VIEWER / "favicon.svg").read_text(encoding="utf-8")
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe="")


def integrity_map(page):
    """The importmap's integrity block, keyed by absolute unpkg URL."""
    block = re.search(r'<script type="importmap">(.*?)</script>', page, re.S)
    if not block:
        sys.exit("no <script type=\"importmap\"> in viewer/instrument.html")
    return json.loads(block.group(1)).get("integrity", {})


def fetch(url, expected):
    with urllib.request.urlopen(url, timeout=60) as r:
        raw = r.read()
    if expected:
        got = "sha384-" + base64.b64encode(hashlib.sha384(raw).digest()).decode()
        if got != expected:
            sys.exit(f"integrity mismatch for {url}\n  want {expected}\n  got  {got}")
    else:
        print(f"  warning: no pinned hash for {url}", file=sys.stderr)
    return raw.decode("utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default=str(VIEWER / "instrument-standalone.html"))
    ap.add_argument("--version", default="0.184.0", help="three.js version to inline")
    # The tab title is a name, not a description of the artefact. It sits in a
    # strip of tabs next to everything else the reader has open.
    ap.add_argument("--title", default="CELL")
    # The tab title and the link-preview title do different jobs. The tab says
    # what the page is; the card is competing in a timeline and has to say what
    # the product is.
    ap.add_argument("--card-title",
                    default="CELL — a hardware wallet that takes your pulse, or your blood")
    ap.add_argument("--description",
                    default="Airgapped signer for Bitcoin and Ethereum. A live pulse, or a "
                            "drop of blood that has to clot while the device watches. Open "
                            "source, 3D printable, about $95 in parts.")
    ap.add_argument("--url", default="https://cell.wei.is",
                    help="canonical URL of the deployed page")
    ap.add_argument("--image",
                    default="https://raw.githubusercontent.com/z0r0z/cell/main/diagrams/social-card.png",
                    help="absolute URL of the 1200x630 link-preview image. Point it at "
                         "your own host if you would rather not depend on GitHub raw.")
    args = ap.parse_args()

    page = SOURCE.read_text(encoding="utf-8")
    hashes = integrity_map(page)

    payloads = {}
    for key, path in CDN.items():
        url = f"https://unpkg.com/three@{args.version}/{path}"
        print(f"fetching {path}")
        payloads[key] = fetch(url, hashes.get(url))

    # The relative self-import is rewritten to a placeholder the bootstrap
    # swaps for the core's blob URL. Two occurrences: an import and a re-export.
    marker = "'./three.core.js'"
    if payloads["p-three"].count(marker) < 2:
        sys.exit("three.module.js no longer imports './three.core.js' as expected")
    payloads["p-three"] = payloads["p-three"].replace(marker, "'THREE_CORE_BLOB_URL'")

    payloads["p-stage"] = (VIEWER / "three-d-stage.js").read_text(encoding="utf-8")
    payloads["p-model"] = (VIEWER / "model.js").read_text(encoding="utf-8")

    style = re.search(r"<style>(.*?)</style>", page, re.S)
    if not style:
        sys.exit("no <style> block in viewer/instrument.html")

    # Lift the markup out of the source page rather than keeping a second copy
    # here. The template used to carry its own hardcoded copy of .wrap, so any
    # element added to instrument.html -- a heading, a fallback for a dead
    # canvas -- was silently missing from the file actually deployed.
    body = re.search(r'<div class="wrap">(?:.*?)\n</div>', page, re.S)
    if not body:
        sys.exit('no <div class="wrap"> block in viewer/instrument.html')

    # An inline block ends at the first '</script' anywhere in its text, even
    # inside a JS comment -- three-d-stage.js's usage docs contain three.
    blocks = "\n".join(
        '<script type="text/plain" id="%s">%s</script>'
        % (k, v.replace("</script", "<\\/script"))
        for k, v in payloads.items()
    )

    html = TEMPLATE % {"title": args.title, "card_title": args.card_title,
                       "description": args.description, "url": args.url,
                       "image": args.image, "style": style.group(1),
                       "body": body.group(0), "payloads": blocks, "boot": BOOT,
                       "favicon": favicon_data_uri()}
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    print(f"\nwrote {out} ({len(html.encode()) / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
