#!/usr/bin/env python3
"""Bundle viewer/instrument.html into one self-contained HTML file.

The point is a file you can paste anywhere -- IPFS, a gist, an email
attachment -- and have it open into the orbitable instrument with no network
access of any kind. three.js r184 is fetched once from unpkg, checked against
the integrity map already pinned in viewer/instrument.html, and inlined.

Every payload rides in a <script type="text/plain"> block and is handed to the
page as a blob: URL at load time. That indirection is what lets a single file
carry ES modules: an import map is built at runtime pointing the bare 'three'
specifier at the blob, before the first module script is inserted.

    python3 tools/build_single_file_viewer.py -o instrument-standalone.html
"""

import argparse
import base64
import hashlib
import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VIEWER = ROOT / "viewer"
SOURCE = VIEWER / "instrument.html"

# id -> URL path under the three package. The hashes are NOT written here on
# purpose: they are read out of instrument.html's integrity map, so the page
# stays the single source of truth for which three.js this project trusts.
CDN = {
    "p-core":  "build/three.core.js",
    "p-three": "build/three.module.js",
    "p-orbit": "examples/jsm/controls/OrbitControls.js",
    "p-obj":   "examples/jsm/exporters/OBJExporter.js",
    "p-gltf":  "examples/jsm/exporters/GLTFExporter.js",
}

BOOT = """
(function () {
  var txt = function (id) { return document.getElementById(id).textContent; };
  var blob = function (src) {
    return URL.createObjectURL(new Blob([src], { type: 'text/javascript' }));
  };

  // three.module.js pulls its own core in by relative path, which cannot
  // resolve from a blob: URL. Rewrite it to the core's blob first.
  var core = blob(txt('p-core'));
  var three = blob(txt('p-three').split('THREE_CORE_BLOB_URL').join(core));

  // The import map has to be installed before any module script loads, so
  // this whole bootstrap is a classic script and runs synchronously.
  var im = document.createElement('script');
  im.type = 'importmap';
  im.textContent = JSON.stringify({ imports: {
    'three': three,
    'three/addons/controls/OrbitControls.js': blob(txt('p-orbit')),
    'three/addons/exporters/OBJExporter.js': blob(txt('p-obj')),
    'three/addons/exporters/GLTFExporter.js': blob(txt('p-gltf'))
  }});
  document.head.appendChild(im);

  var stage = document.createElement('script');  // classic: defines the element
  stage.textContent = txt('p-stage');
  document.head.appendChild(stage);

  var model = document.createElement('script');  // module: builds the instrument
  model.type = 'module';
  model.src = blob(txt('p-model'));
  document.body.appendChild(model);
})();
"""

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s</title>
<link rel="icon" href="%(favicon)s">
<!--
  Self-contained build of viewer/instrument.html -- three.js r184 inlined,
  zero network requests. Drag to orbit, scroll to zoom, and use the toolbar to
  export OBJ or GLB.

  Generated by tools/build_single_file_viewer.py. Do not hand-edit; regenerate.
-->
<style>%(style)s</style>
</head>
<body>
<div class="wrap">
  <three-d-stage name="instrument"></three-d-stage>
  <div class="vignette"></div>
  <a class="repo" href="https://github.com/z0r0z/cell" target="_blank" rel="noopener">github.com/z0r0z/cell</a>
</div>

%(payloads)s

<script>%(boot)s</script>
</body>
</html>
"""


def favicon_data_uri():
    """viewer/favicon.svg as an inline data: URI.

    Percent-encoded rather than base64: it survives the round trip just as
    reliably, stays readable in View Source, and costs a third less.
    """
    svg = (VIEWER / "favicon.svg").read_text(encoding="utf-8")
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe="")


def integrity_map(page):
    """The importmap's integrity block, keyed by absolute unpkg URL."""
    block = re.search(r'<script type="importmap">(.*?)</script>', page, re.S)
    if not block:
        sys.exit("no <script type=\"importmap\"> in viewer/instrument.html")
    return json.loads(block.group(1)).get("integrity", {})


def fetch(url, expected):
    with urllib.request.urlopen(url, timeout=60) as r:
        raw = r.read()
    if expected:
        got = "sha384-" + base64.b64encode(hashlib.sha384(raw).digest()).decode()
        if got != expected:
            sys.exit(f"integrity mismatch for {url}\n  want {expected}\n  got  {got}")
    else:
        print(f"  warning: no pinned hash for {url}", file=sys.stderr)
    return raw.decode("utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default=str(VIEWER / "instrument-standalone.html"))
    ap.add_argument("--version", default="0.184.0", help="three.js version to inline")
    ap.add_argument("--title", default="Cell — instrument, 3D study")
    args = ap.parse_args()

    page = SOURCE.read_text(encoding="utf-8")
    hashes = integrity_map(page)

    payloads = {}
    for key, path in CDN.items():
        url = f"https://unpkg.com/three@{args.version}/{path}"
        print(f"fetching {path}")
        payloads[key] = fetch(url, hashes.get(url))

    # The relative self-import is rewritten to a placeholder the bootstrap
    # swaps for the core's blob URL. Two occurrences: an import and a re-export.
    marker = "'./three.core.js'"
    if payloads["p-three"].count(marker) < 2:
        sys.exit("three.module.js no longer imports './three.core.js' as expected")
    payloads["p-three"] = payloads["p-three"].replace(marker, "'THREE_CORE_BLOB_URL'")

    payloads["p-stage"] = (VIEWER / "three-d-stage.js").read_text(encoding="utf-8")
    payloads["p-model"] = (VIEWER / "model.js").read_text(encoding="utf-8")

    style = re.search(r"<style>(.*?)</style>", page, re.S)
    if not style:
        sys.exit("no <style> block in viewer/instrument.html")

    # An inline block ends at the first '</script' anywhere in its text, even
    # inside a JS comment -- three-d-stage.js's usage docs contain three.
    blocks = "\n".join(
        '<script type="text/plain" id="%s">%s</script>'
        % (k, v.replace("</script", "<\\/script"))
        for k, v in payloads.items()
    )

    html = TEMPLATE % {"title": args.title, "style": style.group(1),
                       "payloads": blocks, "boot": BOOT,
                       "favicon": favicon_data_uri()}
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    print(f"\nwrote {out} ({len(html.encode()) / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
